# Generated by Django 5.2.4 on 2025-07-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='property_id',
            new_name='property',
        ),
    ]
