# Generated by Django 5.2.4 on 2025-09-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
