# Generated by Django 5.2.4 on 2025-09-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-13'),
            preserve_default=False,
        ),
    ]
