# Generated by Django 5.2.4 on 2025-07-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property',
            new_name='property_id',
        ),
    ]
