# Generated by Django 5.2.4 on 2025-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_host_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='verification',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
