# Generated by Django 5.2.4 on 2025-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
